

plot_dir: /mnt/beegfs/bulk/mirror/jyf6/datasets/exploratory_plots

satellite_dataset:
  path: /mnt/beegfs/bulk/mirror/jyf6/datasets/processed_dataset
  grid_area_degrees: 1
  min_soundings: 4
  max_cloud_cover: 0.2
  res: 0.00026949458523585647
  oco2_tile_pixels: 100
  train_tropomi_dates: [2018-07-08, 2018-07-22, 2018-08-05, 2018-08-19]
  train_oco2_dates: [2018-07-08, 2018-07-22, 2018-08-05, 2018-08-19]
  test_dates: [2018-07-08, 2018-07-22, 2018-08-05, 2018-08-19]
  train_sources: [TROPOMI, OCO2]
  test_sources: [OCO2]
  num_tropomi_samples: 1000
  num_oco2_samples: 1000
  num_oco2_repeats: 1
  min_input: -3
  max_input: 3

cfis_dataset:
  path: /mnt/beegfs/bulk/mirror/jyf6/datasets/CFIS
  resolution: 300

baseline_method:
  method: 



DATA_DIR = "/mnt/beegfs/bulk/mirror/jyf6/datasets"
CFIS_DIR = os.path.join(DATA_DIR, "CFIS")
PLOTS_DIR = os.path.join(DATA_DIR, "exploratory_plots")

# Train files
PROCESSED_DATASET_DIR = os.path.join(DATA_DIR, "processed_dataset")
TILE_AVERAGE_TRAIN_FILE = os.path.join(PROCESSED_DATASET_DIR, "tile_info_train.csv")
TILE_AVERAGE_VAL_FILE = os.path.join(PROCESSED_DATASET_DIR, "tile_info_val.csv")
TILE_AVERAGE_TEST_FILE = os.path.join(PROCESSED_DATASET_DIR, "tile_info_test.csv")
BAND_STATISTICS_FILE = os.path.join(PROCESSED_DATASET_DIR, "band_statistics_pixels.csv") #"band_statistics_train.csv")
RES = (0.00026949458523585647, 0.00026949458523585647)
TILE_PIXELS = 100
TILE_SIZE_DEGREES = RES[0] * TILE_PIXELS

# CFIS eval files



TRAIN_TROPOMI_DATES = ["2018-07-08", "2018-07-22", "2018-08-05", "2018-08-19"]
TRAIN_OCO2_DATES = ["2018-07-08", "2018-07-22", "2018-08-05", "2018-08-19"]
TEST_DATES = ["2018-07-08", "2018-07-22", "2018-08-05", "2018-08-19"]


TRAIN_SOURCES = ["TROPOMI", "OCO2"]
TEST_SOURCES = ["OCO2"]
# METHOD = "1a_tropomi_Ridge_Regression"
# METHOD = "1b_tropomi_Gradient_Boosting_Regressor"
# METHOD = "1c_tropomi_MLP"
METHOD = "2a_both_Ridge_Regression"
# METHOD = "2b_both_Gradient_Boosting_Regressor" # + str(MIN_CFIS_SOUNDINGS) + "_soundings"
# METHOD = "2c_both_MLP"
# METHOD = "2d_both_KNN"
# METHOD = "3a_oco2_Ridge_Regression"
# METHOD = "3b_oco2_Gradient_Boosting_Regressor"
# METHOD = "3c_oco2_MLP"
# METHOD = "3_cfis_Linear_Regression"
NUM_TROPOMI_SAMPLES = 1000
NUM_OCO2_SAMPLES = 1000
NUM_OCO2_REPEATS = 1 #round(NUM_TROPOMI_SAMPLES / NUM_OCO2_SAMPLES)
print("METHOD:", METHOD, "- SOURCES:", TRAIN_SOURCES)
print('Num OCO2 repeats:', NUM_OCO2_REPEATS)

PURE_THRESHOLD = 0.6
MIN_SOUNDINGS = 4
MIN_CFIS_SOUNDINGS = 10
MAX_CLOUD_COVER = 0.2
MIN_INPUT = -3
MAX_INPUT = 3
MIN_SIF_CLIP = 0.1
MAX_SIF_CLIP = None
MIN_SIF_PLOT = 0
MAX_SIF_PLOT = 2
NUM_RUNS = 3